INSERT INTO alunos VALUES
(DEFAULT, "Aline da Silva", "PHP"),
(DEFAULT, "Ana Carolina", "PHP"),
(DEFAULT, "Ana Priscila", "PHP"),
(DEFAULT, "Ane Nogueira", "PHP"),
(DEFAULT, "Anna Sarah", "PHP"),
(DEFAULT, "Bianca Gomes", "PHP"),
(DEFAULT, "Camila Rodrigues", "PHP"),
(DEFAULT, "Caren Souza", "PHP"),
(DEFAULT, "Eliane Rodrigues", "PHP"),
(DEFAULT, "Flávia Arroxelas", "Python"),
(DEFAULT, "Gennifer da Silva", "Python"),
(DEFAULT, "Gisleine Nascimento", "Javascript"),
(DEFAULT, "Isabella Ferraz", "Python"),
(DEFAULT, "Joyce da Silva", "Python"),
(DEFAULT, "Larissa de Lima", "C"),
(DEFAULT, "Luciana Bernardes", "Java"),
(DEFAULT, "Luciene Ferreira", "PHP"),
(DEFAULT, "Rayane da Cruz", "PHP"),
(DEFAULT, "Sheila Silva", "SQL"),
(DEFAULT, "Vanessa Rodrigues", "Java"),
(DEFAULT, "Vitória Gomes", "Python"),
(DEFAULT, "Marcio Fuchshuber", "Cobol");
